#! /bin/bash

ANSWER="-"

while [[ true ]]
do

	printf "Type user's \x1B[32mname\x1B[0m to be added:\n"

	read ADD

	USER=( `echo $ADD`)

	sudo useradd -m $USER
	sleep 0.7
	printf "User created.\n"

	while [[ true ]]
	do

		printf "\x1B[0m Do you want add another user (\x1B[32m yes\x1B[0m /\x1B[31m no\x1B[0m )?\n"
		read ANSWER
		if [ "$ANSWER" == "yes" ]
		then
			break
		elif [ "$ANSWER" == "no" ]
		then
			exit
		else
			printf "I hope that was a typo...\n"
			continue
		fi
	done

done
